###
POST http://localhost:7070/register
Content-Type: application/json

{
    "firstName": "Hackman",
    "lastName": "Agyemang",
    "userName": "Joker",
    "email": "kk@gmail.Com",
    "password": "123456"
}