// Keys are generated by the server (u/<ownerId>/<uuid>.webp), never from user input. Every
// provider still refuses anything else, so a bug elsewhere cannot turn into path traversal.
const KEY_PATTERN = /^[a-z0-9][a-z0-9/_-]*\.webp$/;

export const assertSafeKey = (key) => {
    if (typeof key !== "string" || key.length > 255 || key.includes("..") || key.includes("//") || !KEY_PATTERN.test(key)) {
        throw new Error("Unsafe storage key");
    }
};
